steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/duongle-279811/flask-photo-app", "."]
  # Push the image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/duongle-279811/flask-photo-app"]
  # Deploy image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "flask-photo-app"
      - "--image"
      - "gcr.io/duongle-279811/flask-photo-app"
      - "--region"
      - "asia-southeast1"
      - "--platform"
      - "managed"
images:
  - gcr.io/duongle-279811/flask-photo-app
timeout: 1200s